version: "3.7"

services:

  postgres14:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_user_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgres14/data

volumes:
  postgres_data:
    driver: local
